# Generated by Django 5.2.6 on 2026-05-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='next_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
