# Generated by Django 5.2.6 on 2026-05-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_created_at_alter_task_custom_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='previous_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
